version: '3.1'
services:
  nginx:
    container_name: nginx
#    image: nginx:1.17.7
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
    - 80:80

  flask:
    container_name: flask
    build:
      context: ./online_moneywiz
      dockerfile: Dockerfile
#    ports:
#    - 8000:8000